Code review practice
bettercallsully/Code-Review-Project pull request #1
Opened 2021-06-02 20:04 UTC by bettercallsully

- Added HTML mark up from past trials project
- Added linter file configuration for to check for linter errors

2021-06-02 21:45 UTC, bettercallsully commented
- It's crucial that I watch which attributes and tags I use in future projects checking the linter errors as I go instead of checking them after the project is "completed" 💯 
- I need to also be mindful of proper indentation in CSS and HTML files 👍🏾 
- When things get tough do not start from scratch as this can make things worse 🥇 
- Don't be afraid to ask for help, you may find out that someone else has encountered the same issues as you, keep your motivation up, and communicate with your support group. 😄 
- Last but not least, don't be so hard on yourself! 😉

2021-06-03 01:51 UTC, Spayco requested changes
Hi @bettercallsully, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

Your review could use some improvements, please create a new one and double-check that you're following this list:
- GitHub features
  - it's best to utilize the "Review changes" feature from GitHub
  - (from the lesson page) it's required to find at least 2 issues in the code
  - please include those changes using [inline comments](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request)
- Communication: 
  - kindly phrase the comments politely, as suggestions instead of orders. For example:
     * This is a polite suggestion: *"I think it would be better to use semantic tags"*
     * This reads as an order: *"Use semantic tags"*
  - please always include an explanation, a "why", for each requested change. For example:
     * This is a well explained request: *Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible*
     * This request lacks a "why": *Why don't you use an article tag here instead of a div?*
  
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-04 16:14 UTC, bettercallsully reviewed
I would suggest that you try to watch which attributes and tags I use in future projects checking the linter errors as I go instead of checking them after the project is "completed" this will help you in the future in other projects!💯
I need to also be mindful of proper indentation in CSS and HTML files 👍🏾
When things get tough do not start from scratch as this can make things worse 🥇
Don't be afraid to ask for help, you may find out that someone else has encountered the same issues as you, keep your motivation up, and communicate with your support group. 😄
Last but not least, don't be so hard on yourself! 😉

2021-06-04 16:25 UTC, bettercallsully commented on index.html
>          <img alt src="https://www.grammy.com/sites/com/files/styles/news_detail_header/public/ftr-e40-michaeljackson-thumb-ig.jpg?itok=wqWRccRj">
Maybe try to use proper spacing in-between attributes to not trip up the linter errors! - Simple Suggestion

2021-06-04 16:26 UTC, bettercallsully commented on index.html
> -    <figure id="img-div">
Removing unused elements is cool and really not a big deal! Maybe try to find a better use for them in the future! - Optional Suggestion

2021-06-04 16:43 UTC, Temmarie approved these changes
## Status: Approved ✔️ 
### Hi @bettercallsully  , 
#### Good job implementing the changes requested by the previous reviewer. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
#### Congratulations! 🎉 

#### Cheers and Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

2021-06-04 16:50 UTC, merged